// <auto-generated />

namespace Types
{
    using System;
    using System.Collections.Generic;

    
    using Newtonsoft.Json;
    

    public partial class PokeType
    {
        [JsonProperty("damage_relations")]
        public DamageRelations DamageRelations { get; set; }

        [JsonProperty("game_indices")]
        public List<GameIndex> GameIndices { get; set; }

        [JsonProperty("generation")]
        public Generation Generation { get; set; }

        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("move_damage_class")]
        public Generation MoveDamageClass { get; set; }

        [JsonProperty("moves")]
        public List<Generation> Moves { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("names")]
        public List<Name> Names { get; set; }

        [JsonProperty("past_damage_relations")]
        public List<object> PastDamageRelations { get; set; }

    }

    public partial class DamageRelations
    {
        [JsonProperty("double_damage_from")]
        public List<Generation> DoubleDamageFrom { get; set; }

        [JsonProperty("double_damage_to")]
        public List<Generation> DoubleDamageTo { get; set; }

        [JsonProperty("half_damage_from")]
        public List<Generation> HalfDamageFrom { get; set; }

        [JsonProperty("half_damage_to")]
        public List<Generation> HalfDamageTo { get; set; }

        [JsonProperty("no_damage_from")]
        public List<Generation> NoDamageFrom { get; set; }

        [JsonProperty("no_damage_to")]
        public List<Generation> NoDamageTo { get; set; }
    }

    public partial class Generation
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }
    }

    public partial class GameIndex
    {
        [JsonProperty("game_index")]
        public long GameIndexGameIndex { get; set; }

        [JsonProperty("generation")]
        public Generation Generation { get; set; }
    }

    public partial class Name
    {
        [JsonProperty("language")]
        public Generation Language { get; set; }

        [JsonProperty("name")]
        public string NameName { get; set; }
    }

    
}
